### ISSUE TITLE
difference between tesseract.net and tesseract

### ISSUE THREAD

**Issue by mehdiyami** [tvn-cosine/tesseract.net#21]
Hi,

I am dummy completely to tesseract.net
i want to know what is the difference between your project and tesseract project by charlesw on this link
 https://github.com/charlesw/tesseract

which one supports the newest tesseract engine and how can i find a guide about using that

Special thxs

**Comment by Fil1965** [comment]
Hi,

I have exactly the same doubt. I've been running a couple of tests with both versions, and the differences I found so far are:
- Charle's version is using Tesseract 3 and this one version 4.
- Apparently this version needs Tesseract's exe while Charle's doesn't. (That's at least is what I deduced from the sample)
- Charle's version has got some more information.
I'd love to see some more information about this project as using version 4 would be a great benefit.

**Comment by tvn-cosine** [comment]
Both are .net wrappers for the Tesseract libs.  I haven't looked again at charlesw, but this project focuses on Tesseract 4 and not 3.5.

This project however separated out the Leptonica libraries into its own project.  Leptonica is a very powerfull image library and some people are only interested in image manipulation without OCR.

Secondly this project tries to stay close to the original classes as described by Tesseract.  A lot of examples using Tesseract is in C++ and this assist developers with migrating the code over to the .net project.

Due to both projects being just wrappers to Tesseract, it does not matter what project you choose.

Hope this helps
