### ISSUE TITLE
Language auto detection

### ISSUE THREAD

**Issue by Sago92** [tvn-cosine/tesseract.net#5]
Hello,

Is it possiable to auto detect the language inside an image?

Regards

**Comment by tvn-cosine** [comment]
Please look at this project. 

https://github.com/tvn-cosine/languagedetector.net/wiki

**Comment by Sago92** [comment]
The project isn't well documentated hence I need to ask an additional question to that topic. The language detector recognise the language of a string, but my question was related to an image. I need the language information to use Tesseract in the correct way. In my application I want to OCR an Image to get the text information, but without knowing the language, I have to load the tesseract engine with alle languages that are support. Therefor the performance is slow and the initialisation needs a lot of time. To reduce this I would like to know if Tesseract itself is able to detect the language. If not do you know another way to archive that?

**Comment by tvn-cosine** [comment]
Most of the developers in the [tvn-cosine](https://github.com/tvn-cosine) team would argue that [Tesseract](https://github.com/tesseract-ocr/tesseract/wiki) is well documented.  The [Tesseract](https://github.com/tesseract-ocr/tesseract/wiki) team really have done an amazing job from their side.  Simple searches on the web reveals a lot more information due to the sheer amount of people that are already using the [Tesseract](https://github.com/tesseract-ocr/tesseract/wiki) c libraries.

Understand the data type you are using i.e. [Vector graphics](https://en.wikipedia.org/wiki/Vector_graphics).

[We](https://github.com/tvn-cosine) would suggest extracting text based [meta data](https://stackoverflow.com/questions/220097/read-write-extended-file-properties-c/2096315#2096315) from the physical file and send that through the [language detection](https://github.com/tvn-cosine/languagedetector.net/wiki) wrapper to get an idea on the creator of the file.
